---

- name: Create directory for zeroMQ build
  file: path=/zeromq/ state=directory mode=0744


- name: Get zeroMQ tarball
  get_url: url=http://download.zeromq.org/zeromq-3.2.2.tar.gz dest=/zeromq/ mode=0744

- name: Untar and uncompress (g-zip compression) the zeroMQ tarball
  register: zmqresult
  command: tar -xvf zeromq-3.2.2.tar.gz chdir=/zeromq/ creates=/zeromq/zeromq-3.2.2

- name: configure ZMQ
  when: zmqresult|changed
  command: ./configure chdir=/zeromq/zeromq-3.2.2/ 

- name: Make ZMQ
  when: zmqresult|changed
  command: make chdir=/zeromq/zeromq-3.2.2/ 

- name: Make install ZMQ
  when: zmqresult|changed
  command: make install chdir=/zeromq/zeromq-3.2.2/

- name: Create directory for zeroMQ build
  file: path=/nanomsg/ state=directory mode=0744
