---
- name: install deps
  apt: name='{{item}}' state=latest
  with_items:
    - python-pip
    - python-dev

- name: install python module consulate
  pip: name={{ item }}
  with_items:
    - tornado
    - consulate
