---

- name: apply go to perceptors
  hosts: perceptor
  user: root
  vars_files:
   - defaults/elasticsearch.yaml

  roles:
    - { role: golang, tags: ["system"] }
    - { role: ubuntu, tags: ["system"] }
    - { role: elasticsearch, tags: ["system", "elasticsearch"] }
    - { role: zeromq, tags: ["system", "zeromq"] }
    - { role: nanomsg, tags: ["system", "nanomsg"] }
    - { role: goiostat, tags: ["goiostat", "perceptor"] }
    - { role: goforward, tags: ["goforward", "perceptor"] }
    - { role: gomasticate, tags: ["gomasticate", "perceptor"] }
    - { role: consul,
        consul_is_ui: "true",
        consul_is_server: "true",
        consul_bootstrap: "true",
         tags: ["consul"] }


- name: Apply to web
  hosts: web
  user: root
  roles:
    - { role: golang, tags: ["system"] }
    - { role: ubuntu, tags: ["system"] }
    - { role: zeromq, tags: ["system", "zeromq"] }
    - { role: nanomsg, tags: ["system", "nanomsg"] }
    - { role: goiostat, tags: ["goiostat", "perceptor"] }
    - { role: goforward, tags: ["goforward", "perceptor"] }
    - { role: marketing, tags: ["marketing", "web"] }
    - { role: consul,
        consul_is_ui: "false",
        consul_is_server: "false",
        consul_bootstrap: "false",
        consul_servers: ['23.253.159.164'], #should figure out a way to make this dynamic
         tags: ["consul"] }
  
