---

- name: apply go to all servers
  hosts: all
  user: root

  roles:
    - { role: goiostat, tags: ["goiostat", "perceptor"] }
    - { role: golang, tags: ["system"] }
    - { role: centos, tags: ["system"] }
