---

- name: apply go to perceptors
  hosts: perceptor
  user: root
  vars_files:
   - defaults/elasticsearch.yaml

  roles:
    - { role: golang, tags: ["system"] }
    - { role: ubuntu, tags: ["system", "ubuntu"] }
    - { role: elasticsearch, tags: ["system", "elasticsearch"] }
    - { role: zeromq, tags: ["system", "zeromq"] }
    - { role: nanomsg, tags: ["system", "nanomsg"] }
    - { role: goiostat, tags: ["goiostat", "perceptor"] }
    - { role: goforward, tags: ["goforward", "perceptor"] }
    - { role: gomasticate, tags: ["gomasticate", "perceptor"] }
    - { role: consul,
        consul_is_ui: "true",
        consul_is_server: "true",
        consul_bootstrap: "true",
         tags: ["consul"] }


- name: Apply to web
  hosts: web
  user: root
  roles:
    - { role: golang, tags: ["system"] }
    - { role: ubuntu, tags: ["system", "ubuntu"] }
    - { role: zeromq, tags: ["system", "zeromq"] }
    - { role: nanomsg, tags: ["system", "nanomsg"] }
    - { role: goiostat, tags: ["goiostat", "perceptor"] }
    - { role: goforward, tags: ["goforward", "perceptor"] }
    - { role: marketing, tags: ["marketing", "web"] }
    - { role: consul,
        consul_is_ui: "false",
        consul_is_server: "false",
        consul_bootstrap: "false",
        consul_servers: ['23.253.159.164'], #should figure out a way to make this dynamic
         tags: ["consul"] }
    - { role: haskell, tags: ["haskell", "web"] }
    - role: nginx 
      tags: 
       - nginx
       - web
      nginx_http_params:
        sendfile: "on"
        access_log: "/var/log/nginx/access.log"
      nginx_sites:
       - server:
          file_name: marketing
          listen: 8080
          server_name: localhost
          root: "/var/www/marketing/html"
          location1: {name: /, root: "/var/www/marketing/html" }
          location2: {name: /mail, "proxy_set_header X-Real-IP $remote_addr":"",
                                   "proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for":"",
                                   "proxy_set_header Host $host":"",
                                   proxy_pass: "http://0.0.0.0:3000/mail"}
