---

- name: add perceptor user if it doesn't exist
  action: user name=perceptor shell=/sbin/nologin 

- name: install deps
  apt: name=mercurial,git state=latest

- name: clone git
  sudo: true
  sudo_user: capillaryDeploy
  git: repo=git@github.com:CapillarySoftware/goforward.git
       dest="{{ compile }}"
       accept_hostkey=yes
       version=master

- name: compile and build
  sudo: true
  sudo_user: capillaryDeploy
  environment:
    GOPATH: "{{ gopath }}"
    GOROOT: "{{ goroot }}"
    GOBIN: "{{ gobin }}"
    PATH: "{{ path }}"
    INSTALL: "{{ install }}"
  shell: bash ansible_install.sh
         chdir="{{ compile }}"

- name: mk install dir
  command: "mkdir -p {{ install }} creates={{ install }}"

- name: set permissions
  command: "chown  perceptor {{ install }} "

- name: copy binary
  command: "cp -f {{ compile }}/goforward {{ install }}/ "

- name: copy log conf
  command: "cp -f {{ compile }}/seelog.xml {{ install }}/ "

- name: copy conf file
  command: "cp -f {{ compile }}/conf.yaml {{ install }}/ "

- name: copy service file
  template: "src=goforward.conf.j2 dest=/etc/init/goforward.conf owner=root group=root mode=0644"

- name: Start/Restart service
  service: name=goforward state=restarted enabled=yes


