---

- name: install deps
  apt: name=mercurial,git state=latest

- name: clone git
  sudo: true
  sudo_user: capillaryDeploy
  git: repo=git@github.com:CapillarySoftware/goforward.git
       dest="{{ compile }}"
       accept_hostkey=yes
       version=master

- name: compile and build
  sudo: true
  sudo_user: capillaryDeploy
  environment:
    GOPATH: "{{ gopath }}"
    GOROOT: "{{ goroot }}"
    GOBIN: "{{ gobin }}"
    PATH: "{{ path }}"
    INSTALL: "{{ install }}"
  shell: ./ansible_install.sh
         chdir="{{ compile }}"

- name: mk install dir
  command: "mkdir -p {{ install }} creates={{ install }}"

- name: copy binary
  command: "cp -f {{ compile }}/goforward {{ install }}/ "

- name: copy log conf
  command: "cp -f {{ compile }}/seelog.xml {{ install }}/ "


